function(generate_fakewaflock)
    set(fakewaflock_contents "")
    string(APPEND fakewaflock_contents "launch_dir = '${PROJECT_SOURCE_DIR}'\n")
    string(APPEND fakewaflock_contents "run_dir = '${PROJECT_SOURCE_DIR}'\n")
    string(APPEND fakewaflock_contents "top_dir = '${PROJECT_SOURCE_DIR}'\n")
    string(APPEND fakewaflock_contents "out_dir = '${CMAKE_OUTPUT_DIRECTORY}'\n")

    set(fakewaflock_filename)
    if(LINUX)
        set(fakewaflock_filename .lock-waf_linux_build)
    elseif(WIN32)
        set(fakewaflock_filename .lock-waf_win32_build)
    elseif(APPLE)
        set(fakewaflock_filename .lock-waf_darwin_build)
    else()
        message(FATAL_ERROR "Platform not supported")
    endif()

    file(WRITE ${PROJECT_SOURCE_DIR}/${fakewaflock_filename} ${fakewaflock_contents})
endfunction(generate_fakewaflock)