name: "CI"

on: [push]
  #schedule:
#  - cron:  '0 5 * * *'  #daily build at 5AM
jobs:

  Ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get -y install apt-utils
          sudo apt-get -y install git gcc g++ cmake python make ninja-build
          #sudo apt-get -y install qt5-default
          #sudo apt-get -y install gdb valgrind
          sudo apt-get -y install tcpdump
          sudo apt-get -y install curl unzip tar
          sudo apt-get -y install ccache
      - name: Get timestamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Restore ccache
        id: ccache
        uses: actions/cache@v1.1.0
        with:
          path: .ccache
          key: ubuntu-${{steps.time.outputs.time}}
          restore-keys: ubuntu-
      - name: Setup ccache
        run: |
          ccache --set-config=cache_dir="$GITHUB_WORKSPACE/.ccache"
          ccache --set-config=max_size=400M
          ccache --set-config=compression=true
          ccache -z
      - name: Configure CMake
        run: |
          mkdir cmake-cache
          cd cmake-cache
          cmake -DCMAKE_BUILD_TYPE=minsizerel -DNS3_EXAMPLES=ON -DNS3_TESTS=ON -G"Ninja"  ..
      - name: Build ns-3
        run: |
          cd cmake-cache
          ninja
      - name: Print ccache statistics
        run: |
          ccache -s
      - name: Run tests and examples
        if: steps.ccache.outputs.cache-hit != 'true'
        run: python3 test.py --nowaf

  #CodeQL:
  #  name: Analyze
  #  runs-on: ubuntu-latest
  #  needs: Ubuntu
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      language: [ 'cpp' ]
  #      # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
  #      # Learn more:
  #      # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
  #  steps:
  #  - name: Checkout repository
  #    uses: actions/checkout@v2
  #  # Initializes the CodeQL tools for scanning.
  #  - name: Initialize CodeQL
  #    uses: github/codeql-action/init@v1
  #    with:
  #      languages: ${{ matrix.language }}
  #  - name: Perform CodeQL Analysis
  #    uses: github/codeql-action/analyze@v1

  Windows_MinGW:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v1
      # Manual setup
      #- name: Install msys2/mingw64
      #  #steps from https://github.com/msys2/MINGW-packages/blob/master/azure-pipelines.yml
      #  run: |
      #    git clone https://github.com/msys2/msys2-ci-base.git D:\msys64 # they removed this repo :(
      #    D:\msys64\usr\bin\rm -rf D:\msys64\.git
      #    set PATH=D:\msys64\usr\bin;%WINDIR%;%WINDIR%\System32
      #    D:\msys64\usr\bin\pacman --noconfirm -Syyuu
      #    set PATH=D:\msys64\usr\bin;%WINDIR%;%WINDIR%\System32
      #    D:\msys64\usr\bin\pacman --noconfirm --needed -S git base-devel
      #    D:\msys64\usr\bin\pacman --noconfirm -Scc
      #  shell: cmd
      - uses: msys2/setup-msys2@v2
      - name: Install required msys2/mingw64 packages
        run: |
          pacman -S --noconfirm unzip
          pacman -S --noconfirm tar
          pacman -S --noconfirm mingw-w64-x86_64-curl
          pacman -S --noconfirm mingw-w64-x86_64-binutils
          pacman -S --noconfirm mingw-w64-x86_64-cmake
          pacman -S --noconfirm mingw-w64-x86_64-gcc
          pacman -S --noconfirm mingw-w64-x86_64-ninja
          pacman -S --noconfirm mingw-w64-x86_64-python
          pacman -S --noconfirm mingw-w64-x86_64-ccache
          pacman --noconfirm -Scc
      - name: Get timestamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Restore ccache
        id: ccache
        uses: actions/cache@v1.1.0
        with:
          path: .ccache
          key: msys2-${{steps.time.outputs.time}}
          restore-keys: msys2-
      - name: Setup ccache
        run: |
          ccache --set-config=cache_dir="$GITHUB_WORKSPACE/.ccache"
          ccache --set-config=max_size=400M
          ccache --set-config=compression=true
          ccache -z
      - name: Configure CMake
        run: |
          mkdir cmake-cache
          cd cmake-cache
          cmake -DCMAKE_BUILD_TYPE=minsizerel -DNS3_EXAMPLES=ON -DNS3_TESTS=ON -G"Ninja" -DAUTOINSTALL_DEPENDENCIES=ON ..
      - name: Build ns-3
        run: |
          cd cmake-cache
          ninja
      - name: Print ccache statistics
        run: |
          ccache -s
      - name: Run tests and examples
        if: steps.ccache.outputs.cache-hit != 'true'
        run: python test.py --nowaf

  Mac_OS_X:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          brew install ninja cmake gcc@9 ccache #qt5
      - name: Get timestamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Restore ccache
        id: ccache
        uses: actions/cache@v1.1.0
        with:
          path: .ccache
          key: osx_brew-{{steps.time.outputs.time}}
          restore-keys: osx_brew-
      - name: Setup ccache
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          ccache --set-config=cache_dir="$GITHUB_WORKSPACE/.ccache"
          ccache --set-config=max_size=400M
          ccache --set-config=compression=true
          ccache -z
      - name: Configure CMake
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          export CXX=g++-9
          export CC=gcc-9
          mkdir cmake-cache
          cd cmake-cache
          cmake -DCMAKE_BUILD_TYPE=minsizerel -DNS3_EXAMPLES=ON -DNS3_TESTS=ON -G"Ninja" ..
      - name: Build ns-3
        run: |
          export PATH="$PATH" #:/usr/local/opt/qt/bin
          cd cmake-cache
          ninja
      - name: Print ccache statistics
        run: |
          ccache -s
      - name: Run tests and examples
        if: steps.ccache.outputs.cache-hit != 'true'
        run: python3 test.py --nowaf
    #  - name: Clean release with debug artifacts
    #    run: |
    #      rm -Rf ../build
    #      rm -Rf ./*
    #      rm -Rf ../3rd-party/vcpkg
    #      rm ../utils/failed-tests.json

  #Windows_Visual_Studio:   #not working
  #
  #  runs-on: windows-latest
  #
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Install required packages
  #    run: |
  #      ????
  #  - name: Configure CMake
  #    run: |
  #      %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
  #      mkdir cmake-cache
  #      cd cmake-cache
  #      cmake -DCMAKE_BUILD_TYPE=RELEASE -G"Ninja" ..
  #  - name: Build ns-3
  #    run: |
  #      %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
  #      cd cmake-cache
  #      ninja
  #  -  name: Run tests
  #     run: |
  #       python3 ./utils/test-runner-script.py


